package com.bloomtechlabs.coderheroesbea.entities;

import javax.persistence.*;

@Entity
@Table(name = "admins")
public class Admins {
    private int admin_id;
    private Profiles profile;
    /**
     * Constructor.
     * Default constructor is required to have Hibernate initialize the entity.
     */
    public Admins() {

    }

    /**
     * Constructor with admin_id.
     * @param admin_id - primary key, auto-increments, generated by database
     */
    public Admins(int admin_id) {
        this.admin_id = admin_id;
    }

    /**
     * Constructor with all fields.
     * @param admin_id - primary key, auto-increments, generated by database
     * @param profile_id - foreign key (table 'profiles', not null, unique)
     */
    public Admins(int admin_id, Profiles profile) {
        this.admin_id = admin_id;
        this.profile = profile;
    }
    @Id
    @Column(name = "admin_id")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public int getAdmin_id() {
        return admin_id;
    }

    public void setAdmin_id(int admin_id) {
        this.admin_id = admin_id;
    }
    @OneToOne(cascade = CascadeType.REMOVE)
    @JoinColumn(name ="profile_id", nullable = false, unique = true)
    public Profiles getProfile() {
        return profile;
    }

    public void setProfile(Profiles profile) {
        this.profile = profile;
    }
}
