package com.bloomtechlabs.coderheroesbea.entities;

import javax.persistence.*;

@Entity
@Table(name = "conversations")

public class Conversations {
    private int conversation_id;
    private Profiles profile;

    /**
     * Constructor.
     * Default constructor is required to have Hibernate initialize the entity.
     */
    public Conversations() {

    }

    /**
     * Constructor with conversation_id.
     * @param conversation_id - primary key (auto-increments, generated by database)
     */
    public Conversations(int conversation_id) {
        this.conversation_id = conversation_id;
    }

    /**
     * Constructor with all fields.
     * @param conversation_id - primary key (auto-increments, generated by database)
     * @param profile - foreign key (table 'profiles')
     */
    public Conversations(int conversation_id, Profiles profile) {
        this.conversation_id = conversation_id;
        this.profile = profile;
    }

    @Id
    @Column(name = "conversation_id")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public int getConversation_id() {
        return conversation_id;
    }

    public void setConversation_id(int conversation_id) {
        this.conversation_id = conversation_id;
    }

    @ManyToOne(cascade = CascadeType.REMOVE)
    @JoinColumn(name = "profile_id", nullable = false)
    public Profiles getProfile() {
        return profile;
    }

    public void setProfile(Profiles profile) {
        this.profile = profile;
    }
}
