package com.bloomtechlabs.coderheroesbea.entities;

import javax.persistence.*;

@Entity
@Table(name = "instructors_program_types")
public class Instructors_program_types {
    private int instructors_program_types_id;
    private Instructors instructor;

    private Programs programs;
    /**
     * Constructor.
     * Default constructor is required to have Hibernate initialize the entity.
     */
    public Instructors_program_types() {

    }

    /**
     * Constructor with instructors_program_types_id.
     * @param instructors_program_types_id - primary key, auto-increments, generated by database
     */
    public Instructors_program_types(int instructors_program_types_id) {
        this.instructors_program_types_id = instructors_program_types_id;
    }

    /**
     * Constructor with all fields.
     * @param instructors_program_types_id - primary key, auto-increments, generated by database
     * @param instructor - foreign key (table 'instructors', not null)
     * @param programs - foreign key (table 'programs', not null)
     */
    public Instructors_program_types(int instructors_program_types_id, Instructors instructor, Programs programs) {
        this.instructors_program_types_id = instructors_program_types_id;
        this.instructor = instructor;
        this.programs = programs;
    }

    @Id
    @Column(name = "instructors_program_types_id")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public int getInstructors_program_types_id() {
        return instructors_program_types_id;
    }

    public void setInstructors_program_types_id(int instructors_program_types_id) {
        this.instructors_program_types_id = instructors_program_types_id;
    }
    @ManyToOne(cascade = CascadeType.REMOVE)
    @JoinColumn(name ="instructor_id", referencedColumnName = "instructor_id", nullable = false)
    public Instructors getInstructor() {
        return instructor;
    }

    public void setInstructor(Instructors instructor) {
        this.instructor = instructor;
    }

    @OneToOne(cascade = CascadeType.REMOVE)
    @JoinColumn(name ="program_id", referencedColumnName = "program_id", nullable = false)
    public Programs getPrograms() {
        return programs;
    }

    public void setPrograms(Programs programs) {
        this.programs = programs;
    }
}
