package com.bloomtechlabs.coderheroesbea.entities;

import javax.persistence.*;
import java.util.Date;

@Entity
@Table(name = "newsfeed")
public class Newsfeed {
//    newsfeed_id integer NOT NULL DEFAULT nextval('newsfeed_newsfeed_id_seq'::regclass),
//    title character varying(255) COLLATE pg_catalog."default" NOT NULL,
//    link character varying(255) COLLATE pg_catalog."default" NOT NULL,
//    description text COLLATE pg_catalog."default" NOT NULL,
//    posted_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    private int newsfeed_id;
    private String title;
    private String link;
    private String description;
    private Date posted_at;

    /**
     * Constructor.
     * Default constructor is required to have Hibernate initialize the entity.
     */
    public Newsfeed() {

    }

    /**
     * Constructor with newsfeed_id
     * @param newsfeed_id - primary key, auto-increments, generated by database
     */
    public Newsfeed(int newsfeed_id) {
        this.newsfeed_id = newsfeed_id;
    }

    /**
     * Constructor with all fields.
     * @param newsfeed_id - primary key, auto-increments, generated by database
     * @param title - string not null
     * @param link - string not null
     * @param description - string not null
     * @param posted_at - timestamp (autogenerated)
     */
    public Newsfeed(int newsfeed_id, String title, String link, String description, Date posted_at) {
        this.newsfeed_id = newsfeed_id;
        this.title = title;
        this.link = link;
        this.description = description;
        this.posted_at = posted_at;
    }
    @Id
    @Column(name = "newsfeed_id")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public int getNewsfeed_id() {
        return newsfeed_id;
    }

    public void setNewsfeed_id(int newsfeed_id) {
        this.newsfeed_id = newsfeed_id;
    }

    public String getTitle() {
        return title;
    }
    @Column(name = "title", nullable = false)
    public void setTitle(String title) {
        this.title = title;
    }
    @Column(name = "link", nullable = false)
    public String getLink() {
        return link;
    }

    public void setLink(String link) {
        this.link = link;
    }
    @Column(name = "description", nullable = false)
    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }
    @Column(name = "posted_at", columnDefinition = "timestamp default CURRENT_TIMESTAMP")
    public Date getPosted_at() {
        return posted_at;
    }

    public void setPosted_at(Date posted_at) {
        this.posted_at = posted_at;
    }
}
