package com.bloomtechlabs.coderheroesbea.entities;

import javax.persistence.*;

@Entity
@Table(name = "programs")
public class Programs {
    private int program_id;
    private String program_name;
    private String program_description;

    /**
     * Constructor.
     * Default constructor is required to have Hibernate initialize the entity.
     */
    public Programs() {

    }

    /**
     * Constructor with program_id.
     * @param program_id - primary key, auto-increments, generated by database
     */
    public Programs(int program_id) {
        this.program_id = program_id;
    }

    /**
     * Constructor with all fields.
     * @param program_id - primary key, auto-increments, generated by database
     * @param program_name - string (unique)
     * @param program_description - string
     */
    public Programs(int program_id, String program_name, String program_description) {
        this.program_id = program_id;
        this.program_name = program_name;
        this.program_description = program_description;
    }
    @Id
    @Column(name = "program_id")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public int getProgram_id() {
        return program_id;
    }

    public void setProgram_id(int program_id) {
        this.program_id = program_id;
    }
    @Column(name = "program_name", nullable = false, unique = true)
    public String getProgram_name() {
        return program_name;
    }

    public void setProgram_name(String program_name) {
        this.program_name = program_name;
    }
    @Column(name = "program_description", columnDefinition = "text", nullable = false)
    public String getProgram_description() {
        return program_description;
    }

    public void setProgram_description(String program_description) {
        this.program_description = program_description;
    }
}
