package com.bloomtechlabs.coderheroesbea.entities;

import javax.persistence.*;

@Entity
@Table(name = "roles")
public class Roles {
    private int role_id;
    private String role_name;

    /**
     * Constructor.
     * Default constructor is required to have Hibernate initialize the entity.
     */
    public Roles() {

    }

    /**
     * Constructor with role_id.
     * @param role_id - primary key (auto-increments, generated by database)
     */
    public Roles(int role_id) {
        this.role_id = role_id;
    }

    /**
     * Constructor with all fields.
     * @param role_id - primary key (auto-increments, generated by database)
     * @param role_name - string (not nullable, unique)
     */
    public Roles(int role_id, String role_name) {
        this.role_id = role_id;
        this.role_name = role_name;
    }

    @Id
    @Column(name = "role_id")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public int getRole_id() {
        return role_id;
    }

    public void setRole_id(int role_id) {
        this.role_id = role_id;
    }
    @Column(name = "role_name", nullable = false, unique = true)
    public String getRole_name() {
        return role_name;
    }

    public void setRole_name(String role_name) {
        this.role_name = role_name;
    }
}
